---
postgres:
  database: attendance_db
  host: 13.201.69.78
  port: 5432
  user: postgres
  password: password

redis:
  host: 13.201.69.78
  port: 6379
  password: ""


sahjnwkhi

AWS_ACCESS_KEY_ID=AKIAQWERTYUIOPASDFGH
AWS_SECRET_ACCESS_KEY=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