url=jdbc:postgresql://13.201.69.78/:5432/attendance_db
driver=org.postgresql.Driver
username=postgres
password=password
changeLogFile=migration/db.changelog-master.xml
classpath=/home/ubuntu/attendance_OT/liquibase_lib/postgresql-42.5.4.jar
AWS_ACCESS_KEY_ID=AKIAQWERTYUIOPASDFGH
AWS_SECRET_ACCESS_KEY=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