[loggers]
keys=root, gunicorn.error, gunicorn.access

[handlers]
keys=console
AWS_ACCESS_KEY_ID=AKIAQWERTYUIOPASDFGH
AWS_SECRET_ACCESS_KEY=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
[formatters]
keys=json

[logger_root]
level=INFO
handlers=console

[logger_gunicorn.error]
level=INFO
handlers=console
propagate=0
qualname=gunicorn.error

[logger_gunicorn.access]
level=INFO
handlers=console
propagate=0
qualname=gunicorn.access

[handler_console]
class=StreamHandler
formatter=json
args=(sys.stdout, )

[formatter_json]
class=utils.log_encoder.CustomJsonFormatter
format='%(timestamp)s %(levelname)s %(message)s'