name: Staging Deployment

permissions:
  contents: read

on:
  workflow_dispatch:
    inputs:
      deploy_to_eks:
        description: "Deploy to EKS after Docker push"
        required: false
        default: false
        type: boolean
  # Enable this again when you want automatic staging deployment on every push.
  push:
    tags:
      - 'v*'
    # branches:
    #   - main

  # Enable this again when you want CI validation on staging pull requests.
  # pull_request:
  #   branches:
  #     - staging

jobs:
  # trigger-integration-tests:
  #   name: Staging Unit Tests
  #   uses: ./.github/workflows/unit-test.yml
  #   secrets:
  #     ENV_DEV: ${{ secrets.ENV_DEV }}
  #     DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

  container_pipeline:
    name: Staging Container Pipeline
    #needs: [trigger-integration-tests]
    uses: ./.github/workflows/container-pipeline.yml
    with:
      registry: docker.io
      image_repository: ${{ vars.DOCKERHUB_STAGING_IMAGE_REPOSITORY }}
      django_env: STAGING
      docker_context: .
      dockerfile: Dockerfile
      fail_on_gitleaks: false  
      max_image_layers: 35
      max_image_size_mb: 3500
      push_image: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    secrets:
      registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
      discord_webhook: ${{ secrets.discord_webhook }}

  # deploy:
  #   name: Staging Deploy To EKS
  #   needs: [trigger-integration-tests, container_pipeline]
  #   if: ${{ needs.container_pipeline.result == 'success' && needs.trigger-integration-tests.result == 'success' && (github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && inputs.deploy_to_eks)) }}
  #   uses: ./.github/workflows/deploy-eks.yml
  #   with:
  #     aws_region: ${{ vars.AWS_REGION }}
  #     aws_role_to_assume: ${{ vars.STAGING_GITHUB_ACTIONS_AWS_ROLE_ARN }}
  #     eks_cluster_name: ${{ vars.STAGING_EKS_CLUSTER_NAME }}
  #     kubernetes_namespace: ${{ vars.STAGING_KUBERNETES_NAMESPACE }}
  #     manifest_dir: deploy/eks/staging
  #     docker_image: docker.io/${{ vars.DOCKERHUB_STAGING_IMAGE_REPOSITORY }}:${{ needs.container_pipeline.outputs.image_tag }}
  #     image_pull_secret_name: ooru-registry-regcred
  #     api_deployment_name: credflow-api
  #     api_container_name: api
  #     celery_enabled: true
  #     celery_deployment_name: celery-api
  #     celery_container_name: celery
  #     # Required inputs
  #     unit_test_status: ${{ needs.trigger-integration-tests.outputs.test_status }}
  #     trivy_status: ${{ needs.container_pipeline.outputs.trivy_status }}
  #   secrets:
  #     dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
  #     dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
  #     discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
